# Generated by Django 4.0.6 on 2023-07-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_college_created_date_college_modified_date_and_more'),
        ('accounts', '0002_users_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department'),
        ),
    ]
