# Generated by Django 4.0.6 on 2023-07-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='college',
        ),
        migrations.RemoveField(
            model_name='users',
            name='department',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
