# Generated by Django 4.0.6 on 2023-07-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='university_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_contact_no',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_descriptions',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_website',
            new_name='website',
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='master.university')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.college'),
        ),
    ]
