# Generated by Django 4.0.6 on 2023-07-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_university_address_university_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.college'),
        ),
    ]
