# Generated by Django 4.0.6 on 2023-07-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_users_college_remove_users_department_and_more'),
        ('master', '0006_college_created_date_college_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='college',
        ),
        migrations.RemoveField(
            model_name='role',
            name='college',
        ),
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='university',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
